### ISSUE TITLE
camelCase

### ISSUE THREAD

**Issue by andrelima** [jaredreich/notie#10]
Please consider using camelCase for naming variables, etc. All major JavaScript style guides advise this.

Thank you so much.

**Comment by jaredreich** [comment]
Untrue, the javascript community is basically 50/50 on this and it is a matter of preference. The only key factor is consistency throughout a project. They each have their pros and cons - camelCase is shorter because of no underscores but is probably harder to read and retype in most cases (ex. ILikeIllinois vs i_like_illinois)

**Comment by jaredreich** [comment]
I personally use underscores rather than camelCase since it's easier to read, but the Javascript native library uses camelCase so you're probably right. Will change this soon.

**Comment by andrelima** [comment]
I agree with you, snakecase is easier to read — when I came to JavaScript from Ruby, it was a difficult transition to make.

If you use a good programming font like Hack (the best one, IMO), this becomes less of a problem: sourcefoundry.org/hack/

As you can see from the following major JavaScript style guides, camelCase for variables & functions is indeed the JavaScript "way", and CamelCase for class names:

- https://github.com/airbnb/javascript
search for "Naming Conventions"

- https://github.com/felixge/node-style-guide
also search for "Naming Conventions"

- https://google.github.io/styleguide/javascriptguide.xml
search for "Naming"

Also CoffeeScript, which started with snakecase, changed, within its first months of existence, to camelCase to conform with the already established (at the time) JavaScript standards.

**Comment by jaredreich** [comment]
Thanks very much for those sources, I appreciate it.
