### ISSUE TITLE
TypeError: Cannot read property 'appendChild' of null

### ISSUE THREAD

**Issue by abhinavagrawal1995** [jaredreich/notie#102]
I went through the closed issues with the same error, moved the "<script src="js/notie.min.js"></script>" part to the beginning of my site, as well as at the end. None of these worked.

**Comment by jaredreich** [comment]
Not sure what this means:

> moved the "" part to the beginning of my site, as well as at the end

but make sure you place the notie script tag at the very end of your HTML body right before the `</body>` closing tag.

**Comment by abhinavagrawal1995** [comment]
Don't know why the code didn't show up between the quotes.
Yes, I was talking about the notie script part. I had added it AFTER the body is closed. Along with all other JS scripts. Just curious, why does it have to be INSIDE the body?
