### ISSUE TITLE
 I want to prohibit "auto blur" when show alert.

### ISSUE THREAD

**Issue by sawa-zen** [jaredreich/notie#108]
I want to prohibit auto blur when show alert.
Please add a "autoBlur" option.
thanks.

**Comment by jaredreich** [comment]
You need to work on your open source contribution skills.
"I want X, so please add it. Thanks." doesn't usually go very far.

First of all, what does "auto blur" mean?

**Comment by jaredreich** [comment]
Closing due to no response.
