### ISSUE TITLE
Notification on fixed navbar menu

### ISSUE THREAD

**Issue by davidojedalopez** [jaredreich/notie#111]
I am trying to use notie on my site, but I have one problem. 

I have a fixed top navigation menu. Whenever I use notie to show a notification, it gets hidden behind the menu bar. I can make the notification to show OVER the menu, but not just below it because it is fixed.

I tried adding a `top: 50px` style from Javascript at the moment of calling the notie alert, but it gets overridden and returns to a `top:0`. If I try to add `!important` then I can not close the notification by any mean. 

Is there something I can do to allow this behavior? A notie alert below a fixed nav menu.

Here is an example of the notification being hidden behind the menu:
![image](https://cloud.githubusercontent.com/assets/8418542/23045408/171393c8-f46a-11e6-8365-7ea74c784f1c.png)

**Comment by jaredreich** [comment]
This is because your navbar has a `z-index` greater than `999999999`, which is what notie uses. Technically I should make both `z-index` and `top`, and many other things overwriteable via SASS.

**Comment by jaredreich** [comment]
Solved by 7fdd80e
