### ISSUE TITLE
Cancel callback for select

### ISSUE THREAD

**Issue by bbenezech** [jaredreich/notie#112]
Hi Jared,

I need a select cancel callback like the one available for other components:
https://github.com/jaredreich/notie/blob/master/src/notie.js#L338

Looks like it can be consistently added and released with a minor patch bit.

Should I:

- [ ] send a PR 
- [ ] wait for a patch on your side
- [ ] fork :(

Thanks for creating& maintaining Notie.js, really appreciated!

**Comment by jaredreich** [comment]
My goodness, not sure how I missed this! Thanks very much for submitting. I will patch this today.

**Comment by jaredreich** [comment]
Here you are my friend: https://github.com/jaredreich/notie/releases/tag/v4.1.0
