### ISSUE TITLE
Positioning notifications to the bottom window like the "select" example?

### ISSUE THREAD

**Issue by bridgeport** [jaredreich/notie#118]
First, thanks for this great package. I was looking for something like this and only came across alert/modal scripts that threw in slide in notifications on the side. It's nice to have something dedicated to notifications.

There was a previous issue asking about positioning the notifications to the window's bottom: https://github.com/jaredreich/notie/issues/78

Your last message (Dec 28, 2016) said you'd incorporate this into v4. Since version 4 was released a couple days ago and you have an example notifications (select) that does slide up from the bottom window, I'm wondering if the other alerts can do the same?

Is there an option that I'm missing (documented or undocumented) that'll allow this? This would be great to have so that sticky messages can be presented at the footer without obscuring the nav menu.

Thanks.

**Comment by jaredreich** [comment]
Thanks for bringing this up. I set things up in v4 to allow for this but didn't expose it. Will be in next minor release.

**Comment by jaredreich** [comment]
Alright @bridgeport, customizable positions are now in [v4.3.0](https://github.com/jaredreich/notie/releases/tag/v4.3.0). Check out the README for how-to-use.

**Comment by bridgeport** [comment]
This is fantastic. Thanks @jaredreich It works great in desktop and mobile.
