### ISSUE TITLE
Undefined text

### ISSUE THREAD

**Issue by liquidcode94** [jaredreich/notie#121]
Out of the blue it shows the notifications but it only says 'undefined' no other errors are given. And it ignores the text in the alert function.

**Comment by jaredreich** [comment]
You have to be more specific than this. Please show the exact reproduction of your code.

**Comment by TheExeLab** [comment]
# Code:
	
```
<script type="text/javascript" src="https://unpkg.com/jquery@3.1.1/dist/jquery.min.js"></script>
<script type="text/javascript" src="https://unpkg.com/notie@3.9.5/dist/notie.min.js"></script>
<script type="text/javascript">
notie.confirm({
  text: 'Are you sure you want to do that?<br><b>That\'s a bold move...</b>',
  cancelCallback: function () {
	notie.alert({ type: 3, text: 'Aw, why not? :(', time: 2 })
  },
 submitCallback: function () {
        notie.alert({ type: 1, text: 'Good choice! :D', time: 2 })
 }
})
</script>
```

# Final Result: 
![image](https://cloud.githubusercontent.com/assets/7424138/23837746/df75d754-076b-11e7-82a6-1e2cb2b75d03.png)

**Comment by jaredreich** [comment]
That's an older version of notie that does not support that notie.confirm syntax. Use 4.3.0

```
<script type="text/javascript" src="https://unpkg.com/notie@4.3.0/dist/notie.min.js"></script>
```
