### ISSUE TITLE
CDN on README

### ISSUE THREAD

**Issue by roccomuso** [jaredreich/notie#124]
Is it worth putting a CDN link to the main README doc?

`https://cdnjs.cloudflare.com/ajax/libs/notie/4.3.0/notie.min.js`

**Comment by jaredreich** [comment]
Is this more reliable than `https://unpkg.com/notie`?
Does the `cdnjs.cloudflare.com` also host the style files?

**Comment by roccomuso** [comment]
@jaredreich it belongs to the [cdnjs.com](https://cdnjs.com) project.
You can submit also the css.
I guess it's as reliable as `unpkg.com`.
