### ISSUE TITLE
Font size auto

### ISSUE THREAD

**Issue by BilalReffas** [jaredreich/notie#126]
It look's like that "Font size auto-adjusts based on screen size" it's broken ?

**Comment by jaredreich** [comment]
It definitely works. I think the issue is in your implementation.

**Comment by jaredreich** [comment]
See `src/notie.scss`:

```scss
$notie-breakpoint-mobile: 400px !default;
$notie-breakpoint-tablet: 750px !default;
$notie-breakpoint-desktop: 900px !default;
$notie-breakpoint-widescreen: 1050px !default;
$notie-font-size-mobile: 1rem !default;
$notie-font-size-tablet: 1.2rem !default;
$notie-font-size-desktop: 1.4rem !default;
$notie-font-size-widescreen: 1.6rem !default;
```

**Comment by BilalReffas** [comment]
Really strange 🤔 please check this. The device is a `iPhone 6s`

![fullsizerender](https://cloud.githubusercontent.com/assets/8920003/25569208/c26bc75e-2e12-11e7-8e02-4e1ed36f8879.jpg)

**Comment by jaredreich** [comment]
Please check what? I have no idea what you're doing or expecting. Please refer to the documentation, it tells how to change/override styles.

**Comment by BilalReffas** [comment]
Is the font size normal on the attached screenshot?

**Comment by BilalReffas** [comment]
```  html
<link rel="stylesheet" type="text/css" href="https://unpkg.com/notie/dist/notie.min.css">
      <style>
    /* override styles here */
    .notie-container {
      font-size: 4vw;
    }
```
This fixed the issue for me.
