### ISSUE TITLE
Not able to alert with nav bar.

### ISSUE THREAD

**Issue by anchitgupt** [jaredreich/notie#140]
I am using the navbar by the Google material design lite https://getmdl.io/.
With this, it always hiding behind the navbar.
![screen shot 2018-03-17 at 8 03 15 pm](https://user-images.githubusercontent.com/16156148/37556573-47687382-2a1e-11e8-9ab5-22fc658b2a4b.png)

and javascript code I use is this

notie.alert({ type: 4, text: 'Information.', time: 2 })

navbar code is:

`<div id="navbarhead" class="mdl-layout mdl-js-layout">
      <header class="mdl-layout__header">
        <div class="mdl-layout-icon"></div>
        <div class="mdl-layout__header-row">
          <span class="mdl-layout__title">Clean India & Safe India
      	<span class="page_title-span"> | </span>
          <span class="page_title-span"> Log In </span>
          </span>
          <div class="mdl-layout-spacer"></div>
          <nav class="mdl-navigation">
          </nav>
        </div>
      </header>
      </div>`

**Comment by jaredreich** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/z-index

**Comment by anchitgupt** [comment]
Thanx
