### ISSUE TITLE
Notie not defined: Cannot find module "./dist/notie.min.js" in package notie@4.3.1

### ISSUE THREAD

**Issue by Jones-S** [jaredreich/notie#145]
https://unpkg.com/notie@4.3.1

If you go to that link it cannot get the package. Is it a problem on your site, or from unpkg? 

<img width="551" alt="image" src="https://user-images.githubusercontent.com/7059580/42685497-6585c9d8-8693-11e8-8746-72360528461b.png">

**Comment by MartinKolarik** [comment]
Problem with unpkg as https://cdn.jsdelivr.net/npm/notie@4.3.1 works.

**Comment by Jones-S** [comment]
I think it was only down for a bit.
