### ISSUE TITLE
Add AMD, Common modules support and Notie methods should be prototype of Notie function.

### ISSUE THREAD

**Issue by singerxt** [jaredreich/notie#15]
Will be good to add support for modern projects where people use Browserify, ES6 modules etc.
Example

```
var notie = require('notie');

notie.confirm();

// or ES6

import notie from '/notie';

notie.confirm();
```

In my opinion from perfomance reasons and code quality reasons notie should be rewrited to "class" and all methods should be prototype.

```
var notie = new Notie({//config});
Notie.confirm();

// Implementation example

function Notie (config) {
    this.config = config;
}

Notie.prototype.confirm = function (msg) {
   alert(msg);
};
```

:+1: 

[Examples](https://github.com/umdjs/umd/blob/master/templates/returnExportsGlobal.js)

**Comment by jaredreich** [comment]
Thanks to @rrdelaney for PR #16
