### ISSUE TITLE
Add no/cancel callback for confirm and input functions

### ISSUE THREAD

**Issue by singerxt** [jaredreich/notie#18]
Actually confirm function have callback only for success I think could be handy to have callback for fail :-)

**Comment by jaredreich** [comment]
I knew someone would request this ;). Sure thing, I'll implement this soon. Thank you.

**Comment by leroy0211** [comment]
You could instead of calling a parameter as a function. You could merge an object on which you can define your own: 
success, error, final, beforestart, afterstart, etc. handlers. 
Like jQuery uses on an ajax call. 

EG:

```javascript
notie.confirm('Are you sure you want to do that?', 'Yes', 'Cancel', {
     success: function(notie){},
     cancel: function(notie){}, 
     final: function(notie){}
});
```

Or just to make all things configurable as an object:

```javascript
notie.confirm({
    question: "Are you sure you want to do that?",
    options: [
        "Yes": function(notie){ // callback for Yes option },
        "No": function(notie){ // callback for No option },
        "Cancel": function(notie){ // callback for Cancel option }
    ],
    "position": "bottom",
    "fixed":  true
});
```

**Comment by connorjburton** [comment]
I agree the arguments should be an object, however I think that would come with making the library OO.
