### ISSUE TITLE
allow changing defaults

### ISSUE THREAD

**Issue by luisrudge** [jaredreich/notie#32]
without having to copy and paste your excellent lib

**Comment by jaredreich** [comment]
Do you mean you'd like the ability to change the options with javascript?

**Comment by luisrudge** [comment]
yes

**Comment by jaredreich** [comment]
Good suggestion, will implement. Thanks.

**Comment by blackfyre** [comment]
A concept could be much like what sweet alert uses... You can pass a configuration object with the call optionally, and this object if exists would override the libraries defaults. Undersore already has a defaults method for this kind of object merge.

**Comment by natzar** [comment]
Allow changing defaults, added setOptions method, and added a lot of "options.(...)"  :) https://github.com/natzar/notie.js/commit/3f9014b1b4cc11a82ad2a99332d0c40e1ac41e0f  Time to refactor is close ... anyway I like this "factory" approach.

**Comment by fabiocaccamo** [comment]
+1
