### ISSUE TITLE
No manual close/dismiss functionality + subsequent alerts don't work.

### ISSUE THREAD

**Issue by afhammad** [jaredreich/notie#53]
First of all, nice clean library, thanks.

Some feedback:

Showing an alert while a previous one is still visible does nothing. Scenario: I show an alert to notify the user that the changes are being saved, however if the transaction fails i would like to show an error alert but this doesn't work and there is no way I can see of manually closing an active alert.

**Comment by pdeschen** [comment]
FYI, you can actually manually close the active alert by click on it. Not obvious and I would personally like an option to display a dismiss X.
