### ISSUE TITLE
Uncaught TypeError: Cannot read property 'appendChild' of null

### ISSUE THREAD

**Issue by tilight** [jaredreich/notie#56]
Hi, i want to add this into my func.js wich is beeing loaded in the head section.
I need the func js in the head section beause of functions while html is running.
But then i get following error:
Uncaught TypeError: Cannot read property 'appendChild' of null

**Comment by heliohead** [comment]
I have the same error :(
![screenshot 2015-12-19 19 38 36](https://cloud.githubusercontent.com/assets/675604/11915316/38dbde24-a688-11e5-85ee-fce388cd6e89.png)

**Comment by amybvn** [comment]
i moved notie.js to footer then everything work fine.

**Comment by patosai** [comment]
The problem is that the script might get executed before the 'body' element gets parsed, so document.body returns null.
