### ISSUE TITLE
Suggestion: make confirm return true or false depending on selection

### ISSUE THREAD

**Issue by dherran** [jaredreich/notie#60]
So you can use stuff like:

    if(notie.confirm('Are you sure you want to do that?', 'Yes', 'Cancel')) {
      // whatever
    }

Easier and cleaner than a callback and it emulates the default JS confirm. Will try to fork later and push a merge request for review.

**Comment by Dakota628** [comment]
+1

**Comment by jaredreich** [comment]
Great suggestion, I'll implement this no need to fork. Thanks!

**Comment by jaredreich** [comment]
After consideration I feel as though this removes the intuitive functionality of confirm for a very edge-case/small benefit.
