### ISSUE TITLE
Suggestion: Persistent alerts or notifiable-alerts

### ISSUE THREAD

**Issue by willhertz** [jaredreich/notie#65]
Great plugin, clean and simple Just loving it.
I think a a great feature could be to have the ability for showing alerts that are not time-dependant so can be manually dismissed.
Just like a confirmation but with only one button so user aknowledges has read the alert (but no decission is required)
It's like an hybrid between alert and confirmation.

**Comment by jaredreich** [comment]
Good suggestion I'll add this to the list

**Comment by 3ken** [comment]
This is a good feature. Tho I would like to change the property "background_click_dismiss" from a css file instead of the js file. Because this will change when new updates are downloaded with NPM, bower and all other package managers.
