### ISSUE TITLE
Provide Tags

### ISSUE THREAD

**Issue by LordMidi** [jaredreich/notie#66]
Hi! First of all: great Script - I love it!

But why don't you provide tags of your plugin? Using bower it would helpful to have version numbers. If I install your script now I get the master branch. It's best practice to have version numbers of your repo, done with the help of git tags.
Or am I getting something wrong?

Thank you.

**Comment by creynders** [comment]
:+1:

**Comment by pklink** [comment]
:+1:

**Comment by miketeix** [comment]
:+1:

**Comment by kmbriedis** [comment]
This is a must, because now with 4.0.0 released my website failed (4.0.0 has both js and css files, previously there was only js file) and I couldn't say bower to install the same version as there are no release tags for this repo!

**Comment by memark** [comment]
+1
I have spent more or less 8 hours trying to figure out why notie worked on my fellow developer's machine, but not on mine. It turned out we had different versions downloaded, although bower said no new version was available. Please fix proper versioning for bower! (It's already correct for npm as far as i can tell.)

**Comment by creynders** [comment]
@jaredreich why did you close this? There are still no git tags to be found... Maybe you didn't push them?

**Comment by creynders** [comment]
If you're unsure on what needs to happen, let me know, I can help out.

**Comment by jaredreich** [comment]
I did add git tags with this release (3.1.0) but you're right it looks like they didn't push. I think it's because I pushed with the GitHub mac app rather than through CLI with --tags.

Working on this now, my apologies everyone for the inconvenience :(

**Comment by jaredreich** [comment]
Okay I've added tags for 2.1.0, 3.0.0, and 3.1.0 - hopefully this solves the issue. Please let me know if it's working with Bower now. Thanks!

**Comment by memark** [comment]
Thanks, it's looking great now! `npm` and `bower` both report the same available versions.

(However, the version 4.0 mentioned above is not visible in either tool.)
