### ISSUE TITLE
Check if HTML body is ready

### ISSUE THREAD

**Issue by LordMidi** [jaredreich/notie#68]
It would be good, to check if the document is loaded & ready. If I include notie.js in my HTML header it ends up with the error "Uncaught TypeError: Cannot read property 'appendChild' of null" caused by

// Attach notie to the body element
document.body.appendChild(alert_outer);

My recommendation would be to do something like jQuery does to check if the body is ready:
http://stackoverflow.com/questions/978740/javascript-how-to-detect-if-document-has-loaded-ie-7-firefox-3

Ok maybe I would have to do this with a pull request, but I'm not a git pro :-)
Thanks

**Comment by jaredreich** [comment]
Great suggestion, will implement, thanks.

**Comment by kntmrkm** [comment]
:+1:

**Comment by fabianschwarzfritz** [comment]
I think that can be closed?
