### ISSUE TITLE
Separate Logic and Styles

### ISSUE THREAD

**Issue by nojacko** [jaredreich/notie#72]
This is a nice library but it really suffers when customising. For example, rather than a background colour, I'd like to add bottom border (different colour for each type of alert). This isn't possible without modifying the code. This will make updates painful.

I'd recommending removing all the settings variables and creating a default CSS file. The code would just need to change classes of the dom elements based on the status. i.e. To show an alert the CSS would have a class (maybe) classed "notie-show" which would have the CSS animation and this class would be added to the notification container. Also, each alert style should have it's own class. etc... 

`resizeListener` could also be replaced with media queries.

This gives far more flexibility and easier upgrades

**Comment by raphaelparent** [comment]
+1

This would also minimize the cluster created when inspecting elements (all the inline style).

**Comment by jaredreich** [comment]
Ok thanks guys. Sorry for no updates lately I'm out of the country. Updates will come soon.

**Comment by fabiocaccamo** [comment]
+1
