### ISSUE TITLE
Confirm/input with three buttons

### ISSUE THREAD

**Issue by Sigmanor** [jaredreich/notie#76]
Hi. Please add confirm/input notification with three buttons.
For example:
http://i.imgur.com/Jealbdj.png

**Comment by kounelios13** [comment]
@Sigmanor how did you make this photo

**Comment by Sigmanor** [comment]
@kounelios13 Print Screen

**Comment by jaredreich** [comment]
sorry, don't think I'll implement this - please feel free to fork and create your own customizations!
