### ISSUE TITLE
Notifications appear on the bottom of the page.

### ISSUE THREAD

**Issue by devnidhinraj** [jaredreich/notie#81]
The notifications(without style) are appearing on the bottom of the page with a text box. Is there a way to provide the mount element ?

**Comment by jwong-dayspring** [comment]
@devnidhinraj Did you just start using notie? We found that the changes from the last few weeks broke our implementation and the notifications were showing up at the bottom of the page. We had to use a specific commit to get back to ~2.1.0. See https://github.com/jaredreich/notie/issues/82

**Comment by jaredreich** [comment]
fixed with recent tagging+release fixes
