### ISSUE TITLE
Unable to get a specific version of Notie using bower

### ISSUE THREAD

**Issue by gnicol-bzh** [jaredreich/notie#82]
Hello,

We use notie in our project. I have version 2.1.0 on my local server, but version 3.0.0 is now on production server, for it does a `bower install` upon deployment.

In `bower.json`:
```JSON
...
  "dependencies": {
    "jquery": "= 2.1.4",
    "modernizr": "~2.8.2",
    "notie": "*"
  },
...
```

We would like to force to version ~2.1.0 to be sure to not see untested features on production server. But `"notie": "~2.1.0"` doesn't work as it seems there is no versioning available for Notie.js (`bower info notie` returns "No versions available", as there is no [releases on Notie repository](https://github.com/jaredreich/notie/releases)).

**Comment by jwong-dayspring** [comment]
@gnicol-bzh I agree that notie should provide version tags so a version can be set in the bower.json.

There's a workaround though. When you run `bower install` you can specify a git revision. I ran `bower install notie#893d4cf8350bca1b7b3b46903f21702be4ccc747` to get back to the last 2.1.0 commit. This changed the bower.json to:

```
...
  "dependencies": {
    ...
    "notie": "893d4cf8350bca1b7b3b46903f21702be4ccc747"
  },
  "resolutions": {
    "notie": "893d4cf8350bca1b7b3b46903f21702be4ccc747"
  }
...
```

**Comment by gnicol-bzh** [comment]
@jwong-dayspring Thank you for the workaround, it's _"better than nothing"_ ;)

**Comment by jaredreich** [comment]
same as #66 ?

**Comment by gnicol-bzh** [comment]
I can't say if it is exactly the same (I'm not used to tags & version creation), but it seems related ;).
