### ISSUE TITLE
Parametrize Cancel option label in the select function

### ISSUE THREAD

**Issue by lanceschi** [jaredreich/notie#91]
Hi @jaredreich and many compliments for notie,

I would only suggest to consider parametrization of the **Cancel option label** in the **select** function. This is especially useful with language other than english.

Currently I'm manually modifying the label with this raw code:
````
setTimeout(() => { document.getElementById("notie-select-cancel").innerHTML = 'Annuler' });
````
Thanks.

Best regards,
Luca

**Comment by jaredreich** [comment]
I apologize for not including this, great catch. Will be in next patch.
