### ISSUE TITLE
Make confirms / notie responsive (on mobile)

### ISSUE THREAD

**Issue by ynnckstrm** [jaredreich/notie#93]
When a notie confirm is displayed on mobile an the text for yes / no is too long, the text is being shown in several rows, but the boxes do not expand. By that issue the user is not able to (clearly) read the whole text when on mobile.
Screenshot attached.
![screenshot_2016-06-01-14-24-00](https://cloud.githubusercontent.com/assets/19638454/15723701/ffcaa76c-2843-11e6-8348-8199279de3c0.png)

**Comment by jaredreich** [comment]
The better UX approach would be to shorten the text :smile: - this is a very specific case, PR welcome

**Comment by jaredreich** [comment]
Seriously though, the benefits are outweighed by the negatives on this one, the text would have to have some non-trivial calculations to find the width, then adjust the percentage width of the container on the fly. I highly highly recommend using text short enough for the user to read within a fraction of a second (eg. 'Yes', 'No', 'Cancel', etc...). For example, if your confirm statement is "are you sure you want to log out?", if your user wants to log out they will click the green "yes" before even reading the large amount of text within, therefore "yes" would suffice. I'm going to close this request for this reason, hopefully you understand :smile:

**Comment by ynnckstrm** [comment]
So I found a kinda ok fix. I just set the height in notie.css of the confirm input to 100%. The boxes now adapts but only to their own texts. See screenshot below.
![1cc2419312043ca9e3cd579f07028ba5](https://cloud.githubusercontent.com/assets/19638454/15724847/44f7ad3a-2849-11e6-94ff-91a667975cc4.png)
