### ISSUE TITLE
Why did the version jump from 3.2.x to 3.8.x?

### ISSUE THREAD

**Issue by sgwatgit** [jaredreich/notie#96]
First off, thanks for making this lib and maintaining it.

I was looking at the releases and noticed there were no 3.3-3.7 versions. Is there something I'm missing here?

**Comment by jaredreich** [comment]
You're not missing anything...

![I have no idea what I'm doing](http://memesvault.com/wp-content/uploads/I-Have-No-Idea-What-Im-Doing-Dog-02.jpg)
